# Generated by Django 2.2.19 on 2021-11-29 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('picture', models.IntegerField()),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.Group')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты/ов',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=2, on_delete=django.db.models.deletion.SET_NULL, related_name='card_products', to='main.Product')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
